insert into categortias (nome) values ('Missangas & Confecção de Joias');
insert into categortias (nome) values ('Decoração de tecidos');
insert into categortias (nome) values ('Tricô & Suprimentos de Crochê');
insert into categortias (nome) values ('Suprimentos para impressão');
insert into categortias (nome) values ('Estamparia de Suprimentos');
insert into categortias (nome) values ('Produtos de Costura');
insert into categortias (nome) values ('Artesanato & Hobby Tecido');
insert into categortias (nome) values ('Suprimentos para agulhas');
insert into categortias (nome) values ('Artes, Ofícios e Costura');
insert into categortias (nome) values ('Pintura, Desenho e Suprimentos de Arte');
insert into categortias (nome) values ('Suprimentos Artesanais e Materiais');
insert into categortias (nome) values ('Suprimentos para embrulho de presente');
insert into categortias (nome) values ('Decorações de Festa');
insert into categortias (nome) values ('Tintas Automotivas e Suprimentos para Tintas');
insert into categortias (nome) values ('Equipamentos para Serviços Pesados e Veículos Comerciais');
insert into categortias (nome) values ('Pneus Automotivos e Rodas');
insert into categortias (nome) values ('Ferramentas Automotivas e Equipamentos');
insert into categortias (nome) values ('Peças e Acessórios de Performance Automotiva');
insert into categortias (nome) values ('Cuidados com o carro');
insert into categortias (nome) values ('Óleos e Fluidos');
insert into categortias (nome) values ('Peças de Reposição Automotivas');
insert into categortias (nome) values ('Luzes, Lâmpadas e Indicadores');
insert into categortias (nome) values ('Acessórios para interiores automotivos');
insert into categortias (nome) values ('Acessórios Automotivos Externos');
insert into categortias (nome) values ('Mercadoria para entusiastas automotivos');
insert into categortias (nome) values ('Eletrônica Automotiva e Acessórios');
insert into categortias (nome) values ('RV Parts &Acessórios');
insert into categortias (nome) values ('Motocicleta');
insert into categortias (nome) values ('Produtos para Fraldas para Bebês');
insert into categortias (nome) values ('Suprimentos de alimentação para bebês');
insert into categortias (nome) values ('Gravidez & Produtos para Maternidade');
insert into categortias (nome) values ('Cadeirinhas para Carros de Segurança Infantil e Acessórios');
insert into categortias (nome) values ('Produtos de segurança para bebês');
insert into categortias (nome) values ('Produtos para treinamento de toalete');
insert into categortias (nome) values ('Produtos para Cuidados com o Bebê');
insert into categortias (nome) values ('Equipamento de viagem para bebés');
insert into categortias (nome) values ('Atividade do bebê e produtos de entretenimento');
insert into categortias (nome) values ('Presentes de Bebê');
insert into categortias (nome) values ('Papelaria para Bebês');
insert into categortias (nome) values ('Mobiliário de Creche, Roupa de Cama e Decoração');
insert into categortias (nome) values ('Bebê');
insert into categortias (nome) values ('Infantil Roupas e Calçados');
insert into categortias (nome) values ('Carrinhos de bebê e acessórios');
insert into categortias (nome) values ('Beleza e Cuidados Pessoais');
insert into categortias (nome) values ('Perfumes e Fragrâncias');
insert into categortias (nome) values ('Produtos para cuidados com o cabelo');
insert into categortias (nome) values ('Maquiagem');
insert into categortias (nome) values ('Produtos de cuidados da pele');
insert into categortias (nome) values ('Ferramentas de Beleza e Acessórios');
insert into categortias (nome) values ('Produtos para Cuidados com Pé, Mão e Unhas');
insert into categortias (nome) values ('Produtos de Higiene Pessoal');
insert into categortias (nome) values ('Produtos de barbear e depilação');
insert into categortias (nome) values ('Servidores de Computador');
insert into categortias (nome) values ('Armazenamento de dados');
insert into categortias (nome) values ('Monitores de computador');
insert into categortias (nome) values ('Computadores & Tablets');
insert into categortias (nome) values ('Peças de reposição de comprimidos');
insert into categortias (nome) values ('Redes de Computadores');
insert into categortias (nome) values ('Componentes do computador');
insert into categortias (nome) values ('Acessórios para Tablets');
insert into categortias (nome) values ('Acessórios para laptop');
insert into categortias (nome) values ('Componentes externos do computador');
insert into categortias (nome) values ('Tecnologia vestível');
insert into categortias (nome) values ('Televisores e Produtos de Vídeo');
insert into categortias (nome) values ('GPS & Navegação');
insert into categortias (nome) values ('Fones de ouvido & Earbuds');
insert into categortias (nome) values ('Eletrônica de Escritório');
insert into categortias (nome) values ('Áudio portátil & Vídeo');
insert into categortias (nome) values ('Leitores de eBook e Acessórios');
insert into categortias (nome) values ('Celulares e Acessórios');
insert into categortias (nome) values ('Acessórios e Suprimentos');
insert into categortias (nome) values ('Projetores de vídeo');
insert into categortias (nome) values ('Eletrônica veicular');
insert into categortias (nome) values ('Câmera & Foto');
insert into categortias (nome) values ('Segurança e Equipamentos de Vigilância');
insert into categortias (nome) values ('Computadores');
insert into categortias (nome) values ('Home Áudio e Produtos de Teatro');
insert into categortias (nome) values ('Consoles de videogame e acessórios');
insert into categortias (nome) values ('Roupas para Meninos');
insert into categortias (nome) values ('Acessórios para Meninos');
insert into categortias (nome) values ('Joias para meninos');
insert into categortias (nome) values ('Relógios para Meninos');
insert into categortias (nome) values ('Sapatos para Meninos');
insert into categortias (nome) values ('Roupas Femininas');
insert into categortias (nome) values ('Acessórios para Meninas');
insert into categortias (nome) values ('Joias Femininas');
insert into categortias (nome) values ('Relógios para Meninas');
insert into categortias (nome) values ('Sapatos Femininos');
insert into categortias (nome) values ('Uniformes Escolares para Meninas');
insert into categortias (nome) values ('Bolsas de viagem');
insert into categortias (nome) values ('Sacolas de Viagem');
insert into categortias (nome) values ('Sacos de Vestuário');
insert into categortias (nome) values ('Conjuntos de Bagagem');
insert into categortias (nome) values ('Malas');
insert into categortias (nome) values ('Acessórios de Viagem');
insert into categortias (nome) values ('Guarda-chuvas');
insert into categortias (nome) values ('Mochilas');
insert into categortias (nome) values ('Bagagem');
insert into categortias (nome) values ('Bolsas para laptop');
insert into categortias (nome) values ('Vestuário Masculino');
insert into categortias (nome) values ('Acessórios Masculinos');
insert into categortias (nome) values ('Relógios Masculinos');
insert into categortias (nome) values ('Calçados Masculinos');
insert into categortias (nome) values ('Vestuário Feminino');
insert into categortias (nome) values ('Bolsas Femininas');
insert into categortias (nome) values ('Acessórios Femininos');
insert into categortias (nome) values ('Relógios Femininos');
insert into categortias (nome) values ('Calçados Femininos');
insert into categortias (nome) values ('Joias Femininas');
insert into categortias (nome) values ('Mobiliário Infantil');
insert into categortias (nome) values ('Cartões-presente');
insert into categortias (nome) values ('Produtos de higiene bucal');
insert into categortias (nome) values ('Produtos Visão');
insert into categortias (nome) values ('Produtos de Bem-Estar e Relaxamento');
insert into categortias (nome) values ('Produtos para Cuidados com o Bebê e Crianças');
insert into categortias (nome) values ('Suprimentos Domésticos');
insert into categortias (nome) values ('Produtos para cuidados com a saúde');
insert into categortias (nome) values ('Dieta & Nutrição Esportiva');
insert into categortias (nome) values ('Suprimentos Médicos de Uso Doméstico e Equipamentos');
insert into categortias (nome) values ('Produtos de bem-estar sexual');
insert into categortias (nome) values ('Saúde e Domicílio');
insert into categortias (nome) values ('Produtos de Nutrição Esportiva');
insert into categortias (nome) values ('Papelaria & Suprimentos para Embrulho de Presente');
insert into categortias (nome) values ('Produtos para Portas Comerciais');
insert into categortias (nome) values ('Produtos de Transmissão de Energia');
insert into categortias (nome) values ('Materiais Industriais');
insert into categortias (nome) values ('Industrial Hardware');
insert into categortias (nome) values ('Produtos Abrasivos e de Acabamento');
insert into categortias (nome) values ('Adesivos Industriais, Selantes e Lubrificantes');
insert into categortias (nome) values ('Produtos para Movimentação de Materiais');
insert into categortias (nome) values ('Testar, Medir e Inspecionar');
insert into categortias (nome) values ('Energia Industrial & Ferramentas Manuais');
insert into categortias (nome) values ('Hidráulica, Pneumática e Hidráulica');
insert into categortias (nome) values ('Filtração');
insert into categortias (nome) values ('Componentes Eletrônicos');
insert into categortias (nome) values ('Laboratório e Produtos Científicos');
insert into categortias (nome) values ('Zeladoria e Abastecimento de Saneamento');
insert into categortias (nome) values ('Produtos de Segurança e Saúde Ocupacional');
insert into categortias (nome) values ('Ferramentas de Corte');
insert into categortias (nome) values ('Fixadores');
insert into categortias (nome) values ('Materiais para Educação Científica');
insert into categortias (nome) values ('Equipamentos de Food Service e Suprimentos');
insert into categortias (nome) values ('Produtos de Manufatura Aditiva');
insert into categortias (nome) values ('Suprimentos médicos profissionais');
insert into categortias (nome) values ('Suprimentos Odontológicos Profissionais');
insert into categortias (nome) values ('Embalagem e Envio de Suprimentos');
insert into categortias (nome) values ('Equipamentos para lojas de varejo e equipamentos');
insert into categortias (nome) values ('Industrial e Científica');
insert into categortias (nome) values ('Produtos de Banho');
insert into categortias (nome) values ('Roupa de cama');
insert into categortias (nome) values ('Home decoração Produtos');
insert into categortias (nome) values ('Mobiliário');
insert into categortias (nome) values ('Material de limpeza doméstica');
insert into categortias (nome) values ('Iluminação Doméstica e Ventiladores de Teto');
insert into categortias (nome) values ('Cozinha e Jantar');
insert into categortias (nome) values ('Aquecimento, Resfriamento e Qualidade do Ar');
insert into categortias (nome) values ('Loja Infantil em Casa');
insert into categortias (nome) values ('Armazenamento doméstico & Organização');
insert into categortias (nome) values ('Arte de parede');
insert into categortias (nome) values ('Aspiradores de pó e cuidados com o piso');
insert into categortias (nome) values ('Produtos de Engomadoria');
insert into categortias (nome) values ('Suprimentos para Festas');
insert into categortias (nome) values ('Suprimentos para pássaros de estimação');
insert into categortias (nome) values ('Suprimentos Cat');
insert into categortias (nome) values ('Suprimentos para cães');
insert into categortias (nome) values ('Peixes e Animais de Estimação Aquáticos');
insert into categortias (nome) values ('Suprimentos para cavalos');
insert into categortias (nome) values ('Répteis e suprimentos para anfíbios');
insert into categortias (nome) values ('Suprimentos para Pequenos Animais');
insert into categortias (nome) values ('Casa Inteligente: Novos Dispositivos Inteligentes');
insert into categortias (nome) values ('Casa Inteligente: Assistentes de Voz e Hubs');
insert into categortias (nome) values ('Casa Inteligente: Fechaduras Inteligentes e Entrada');
insert into categortias (nome) values ('Casa Inteligente: Entretenimento Doméstico');
insert into categortias (nome) values ('Casa Inteligente: Wi-Fi e Rede');
insert into categortias (nome) values ('Casa Inteligente: Câmeras e Sistemas de Segurança');
insert into categortias (nome) values ('Casa Inteligente: Iluminação');
insert into categortias (nome) values ('Casa Inteligente: Plugues e Tomadas');
insert into categortias (nome) values ('Casa Inteligente: Aspiradores e Mops');
insert into categortias (nome) values ('Termostatos domésticos inteligentes - Verificador de Compatibilidade');
insert into categortias (nome) values ('Casa Inteligente: Gramado e Jardim');
insert into categortias (nome) values ('Casa Inteligente: Outras Soluções');
insert into categortias (nome) values ('Casa Inteligente - Aquecimento e Refrigeração');
insert into categortias (nome) values ('Esportes & Fitness');
insert into categortias (nome) values ('Recreação ao ar livre');
insert into categortias (nome) values ('Esportes & Ar Livre');
insert into categortias (nome) values ('Eletrodomésticos');
insert into categortias (nome) values ('Bombas e Equipamentos Hidráulicos');
insert into categortias (nome) values ('Pintura, Tratamentos de Parede e Suprimentos');
insert into categortias (nome) values ('Segurança & Segurança');
insert into categortias (nome) values ('Lâmpadas');
insert into categortias (nome) values ('Ferramentas Elétricas & Ferramentas Manuais');
insert into categortias (nome) values ('Utensílios de cozinha e banho');
insert into categortias (nome) values ('Iluminação & Ventiladores de Teto');
insert into categortias (nome) values ('Equipamentos Elétricos');
insert into categortias (nome) values ('Hardware');
insert into categortias (nome) values ('Material de Construção');
insert into categortias (nome) values ('Medição & Layout');
insert into categortias (nome) values ('Solda & Solda');
insert into categortias (nome) values ('Ferramentas');
insert into categortias (nome) values ('Suprimentos para festas infantis');
insert into categortias (nome) values ('Figuras de Brinquedo e Conjuntos de jogos');
insert into categortias (nome) values ('Novidade Brinquedos & Diversões');
insert into categortias (nome) values ('Suprimentos de Artes e Artesanato');
insert into categortias (nome) values ('Brinquedos de construção');
insert into categortias (nome) values ('Bonecas e Acessórios');
insert into categortias (nome) values ('Eletrônica Infantil');
insert into categortias (nome) values ('Jogos & Acessórios');
insert into categortias (nome) values ('Brinquedos de Aprendizagem e Educação');
insert into categortias (nome) values ('Fantoches e Teatros de Marionetas');
insert into categortias (nome) values ('Enigmas');
insert into categortias (nome) values ('Esportes e Brinquedos ao Ar Livre');
insert into categortias (nome) values ('bichos de pelúcia e brinquedos de pelúcia');
insert into categortias (nome) values ('Brinquedos para bebês e crianças');
insert into categortias (nome) values ('Triciclos, Scooters e Vagões');
insert into categortias (nome) values ('Brinquedos de dedo');
insert into categortias (nome) values ('Conjuntos de jogos de veículos de brinquedo');
insert into categortias (nome) values ('Brincadeiras Infantis Trens e Bondes');
insert into categortias (nome) values ('Brincadeiras Infantis Caminhões');
insert into categortias (nome) values ('Carros de Brincar com Crianças e Carros de Corrida');
insert into categortias (nome) values ('Barcos de Brincadeiras Infantis');
insert into categortias (nome) values ('Ônibus para crianças');
insert into categortias (nome) values ('Tratores Infantis');
insert into categortias (nome) values ('Carros Caça-Níqueis, Pistas de Corrida e Acessórios');
insert into categortias (nome) values ('Sony PSP Jogos, Consoles e Acessórios');
insert into categortias (nome) values ('Nintendo DS Jogos, Consoles e Acessórios');
insert into categortias (nome) values ('Jogos PlayStation 3, Consoles e Acessórios');
insert into categortias (nome) values ('Jogos Wii, Consoles e Acessórios');
insert into categortias (nome) values ('Jogos Xbox 360, Consoles e Acessórios');
insert into categortias (nome) values ('Jogos para Mac & Acessórios');
insert into categortias (nome) values ('Nintendo 3DS & 2DS Consoles, Jogos e Acessórios');
insert into categortias (nome) values ('Sistemas Legados');
insert into categortias (nome) values ('Jogos PlayStation Vita, Consolas e Acessórios');
insert into categortias (nome) values ('Jogos Wii U, Consoles e Acessórios');
insert into categortias (nome) values ('Jogos PlayStation 4, Consoles e Acessórios');
insert into categortias (nome) values ('Jogos Xbox One, Consoles e Acessórios');
insert into categortias (nome) values ('Jogos eletrônicos');
insert into categortias (nome) values ('Serviços de Jogos de Vídeo Online');
insert into categortias (nome) values ('Hardware de Realidade Virtual e Acessórios');
insert into categortias (nome) values ('Nintendo Switch Consoles, Jogos e Acessórios');
insert into categortias (nome) values ('Consolas, Jogos e Acessórios PlayStation 5');
insert into categortias (nome) values ('Xbox Series X & S Consoles, Jogos e Acessórios');
insert into categortias (nome) values ('Jogos para PC & Acessórios');
insert into categortias (nome) values ('Roupas para Meninas e Sapatos');
insert into categortias (nome) values ('Uniformes Escolares para Meninos');
